version: '3.7'
services:
    development:
        build: .
        env_file: .env
        volumes:
            - .:/src/link
        entrypoint: ''
    test:
        build: .
        volumes:
            - .:/src/link
            - /var/run/docker.sock:/var/run/docker.sock
        entrypoint: "pytest"
        networks:
            - test_runner_network
    mypy:
        build: .
        volumes:
            - .:/src/link
        command: "mypy /src/link"
networks:
    test_runner_network:
        name: test_runner_network
