version: '3.7'
services:
    development:
        build: .
        env_file: .env
        entrypoint: ''
    test:
        build: .
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        entrypoint: "pytest"
        networks:
            - test_runner_network
networks:
    test_runner_network:
        name: test_runner_network
