test_runner:
    build: .
    volumes:
        - .:/src/link
        - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: "pytest"
    hostname: test_runner.docker
    dns:
        - 172.0.0.10
    networks:
        - test_runner_network

networks:
    test_runner_network:
        name: test_runner_network
