name: Test

on:
  push:
    branches: [ master, fix_coverage_report ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and generate coverage report
      run: docker-compose run test --cov --cov-report=xml
    - name: Upload coverage report to Codecov
      run:  bash <(curl -s https://codecov.io/bash) 
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
